import { MigrationInterface, QueryRunner } from 'typeorm'
import { v4 as uuidv4 } from 'uuid'

export default class SeedActionObject1699999999999 implements MigrationInterface {
  name = 'SeedActionObject1699999999999'

  public async up(queryRunner: QueryRunner): Promise<void> {
    const names = [
      'ABONO DE PERMANÊNCIA',
      'AÇÃO CIVIL PÚBLICA',
      'Ação Danos Dispensa Discriminatória.',
      'AÇÃO DE ALIMENTOS',
      'AÇÃO DE COBRANÇA REFERENTE A VALORES NÃO RECEBIDOS',
      'AÇÃO DE EMISSÃO DE PAGAMENTO NÃO RECEBIDO',
      'AÇÃO DE EXECUÇÃO DE TÍTULO EXTRAJUDICIAL',
      'AÇÃO DE EXIBIÇÃO DE DOCUMENTOS',
      'AÇÃO DE FIXAÇÃO DE ALIMENTOS',
      'AÇÃO DE GUARDA',
      'AÇÃO DE INDENIZAÇÃO POR DANOS',
      'AÇÃO DE LIBERAÇÃO DOS VALORES NÃO RECEBIDOS',
      'Ação Rescisória',
      'ACIDENTE DE TRABALHO',
      'ACOMPANHAR A EXECUÇÃO',
      'ACUMULO DE FUNÇÃO',
      'Adicional de Periculosidade',
      'Adicional Noturno',
      'AGENTE PENITENCIARIO',
      'AGRAVO DE INSTRUÇÃO',
      'AGRAVO DE INSTRUMENTO',
      'AGUARADNDO JULGAMENTO  AGRAVO',
      'ALVARÁ JUDICIAL',
      'AMPARO AO DEFICIENTE',
      'AMPARO SOCIAL',
      'Anotação/Baixa/Retificação',
      'Anulação / Nulidade de Ato ou',
      'APOSENTADORIA',
      'Aposentadoria da Pessoa com Deficiência por Idade',
      'APOSENTADORIA ESPECIAL',
      'APOSENTADORIA HIBRÍDA',
      'APOSENTADORIA POR IDADE',
      'APOSENTADORIA POR IDADE URBANA',
      'APOSENTADORIA POR INCAPACIDADE PERMANENTE',
      'APOSENTADORIA POR TEMPO DE CONTRIBUIÇÃO',
      'APOSENTADORIA RURAL',
      'APOSENTADORIA URBANA',
      'AUXÍLIO ACIDENTE',
      'AUXÍLIO-ACIDENTE',
      'AUXILIO DOENÇA',
      'AUXÍLIO DOENÇA',
      'AUXILIO DOENÇA ACIDENTÁRIO',
      'AUXILIO POR INCAPACIDADE TEMPORARIA',
      'AUXILIO RECLUSÃO',
      'AUXÍLIO RECLUSÃO',
      'Averbação/Cômputo de Tempo de Serviço com Base em',
      'B - 31',
      'B-32',
      'B-41',
      'B - 42',
      'B - 46',
      'B - 87',
      'B 91',
      'B 94',
      'Babá',
      'BAP COM DEFICIENTE',
      'BENEFÍCIO ASSISTENCIAL PARA PESSOA COM DEFICIÊNCIA',
      'BENEFÍCIO DE AMPARO ASSISTENCIAL',
      'BENEFÍCIO DE AMPARO ASSISTENCIAL AO IDOSO',
      'Beneficio de Prestação Continuada a Pessoa com Def',
      'BPC',
      'BPC DEFICIENTE',
      'BPC IDOSO',
      'BPC-IDOSO',
      'BPC-LOAS',
      'C',
      'Cadastrar ou Renovar Representante Legal',
      'Carta Precatória',
      'Centralizador',
      'CIVEL',
      'COBRANÇA  PARCELAS RETROATIVAS',
      'Compra e Venda',
      'concessão',
      'CONCESSÃO DE AUXÍLIO',
      'CONCESSÃO DE AUXILIO POR INCAPACIDADE',
      'CONCESSÃO DE AUXÍLIO POR INCAPACIDADE',
      'CONCESSÃO DE AUXILIO POR INCAPACIDADE  TEMPORÁRIA',
      'CONCURSO PUBLICO',
      'Condições Degradantes',
      'Consignação em pagamento',
      'Contratos Bancários',
      'CONVERSÃO DE BENEFÍCIO ASSISTE',
      'CORREIÇÃO PARCIAL OU RECLAMAÇÃO CORREICIONAL',
      'CUMPRIMENTO DE SENTENÇA',
      'Cumprimento provisório de sentença',
      'CURATELA',
      'D',
      'DANO ESTETICO',
      'DANO MORAL',
      'DANO MORAL - LUCRO CESSANTE',
      'Danos indígenas',
      "danos indígenas + danos 'normais'",
      'DANOS MATERIAS E MORAIS',
      'danos morais',
      'Danos morais novo',
      'Décimo Terceiro Salário',
      'Décimo Terceiro Salário Propor',
      'Desconfiguração de Justa Causa',
      'DESVIO DE FUNÇÃO',
      'Devolução / Entrega de Objetos',
      'Dispensa Discriminatória',
      'DIVÓRCIO LITIGIOSO',
      'Doença Ocupacional',
      'DPVAT',
      'Embargos de Terceiros',
      'Empreitada',
      'Estabilidade Acidentária',
      'ESTABILIDADE SINDICAL',
      'Excesso de Penhora',
      'EXECUÇÃO DE CONTRATO DE CESSÃO',
      'EXECUÇÃO DE HONORARIOS',
      'EXECUÇÃO FISCAL',
      'EXECUÇÃO PREVIDENCIÁRIA',
      'EXECUÇÃO PROVISÓRIA EM AUTOS SUPLEMENTARES',
      'FGTS',
      'FGTS sacado indevidamente',
      'Guias do Seguro Desemprego',
      'HABILITAÇÃO',
      'HORAS EXTRAS',
      'HORAS IN ITINERE',
      'IMISSÃO DE POSSE',
      'IMISSÃO NA POSSE',
      'INDENIZAÇÃO',
      'INDENIZAÇÃO DANO MATERIAL',
      'Indenização por Danos Morais e Materiais',
      'INSALUBRIDADE',
      'INVENTÁRIO',
      'LOAS-DEF',
      'LOAS - IDOSO',
      'Mandado de Segurança',
      'OBRIGAÇÃO DE FAZER',
      'OBRIGAÇÃO DE NÃO FAZER',
      'OUTROS',
      'PAB',
      'Pagamento em Consignação',
      'PARCELAS: COMISSÕES',
      'Pedido de Demissão',
      'Penhora / Depósito/ Avaliação',
      'Penhora Online / BACEN JUD',
      'PENSÃO POR MORTE',
      'PENSÃO POR MORTE URBANA',
      ': Policial Militar e Civil',
      'Processo Administrativo MPT',
      'PROCESSO OAB',
      'PRORROGAÇÃO',
      'REABILITAÇÃO PROFISSIONAL',
      'REATIVAÇÃO DE BENEFICIO',
      'REATIVAR BENEFICIO',
      'RECONHECIMENTO DE PATERNIDADE',
      'RECONHECIMENTO DE VINCULO',
      'RECONHECIMENTO E DISSOLUÇÃO DE UNIÃO ESTÁVEL',
      'Recuperação Judicial',
      'RECURSO ORDINARIO',
      'Reestabelimento Aposentadoria por Invalidez',
      'RESCISÃO DO CONTRATO',
      'Rescisão Indireta',
      'Ressarcimento ao Erário',
      'RESTABELECIMENTO  DE BENEFÍCIO ASSISTENCIAL',
      'RESTABELECIMENTO DE BENEFÍCIO ASSISTENCIAL',
      'RESTABELECIMENTO DE BENEFÍCIO POR INCAPACIDADE',
      'RESTABELECIMENTO DE PENSÃO POR MORTE',
      'RESTITUIÇÃO DE VALORES',
      'Retificação da Certidão',
      'REVISÃO',
      'REVISÃO DA VIDA TODA',
      'Revisão de Aposentadoria',
      'Revisão de Contrato',
      'Roubo Majorado',
      'SALARIO',
      'SALARIO MATERNIDADE',
      'SALÁRIO MATERNIDADE',
      'SALARIO MATERNIDADE URBANO',
      'SEGURO DEFESO',
      'Seguro Desemprego',
      'SEGURO DE VIDA',
      'Seguro DPVAT',
      'SLARIO MATERNIDADE',
      'Solicitação de Acréscimo de 25%',
      'TESTEMUNHA',
      'TUTELA E GUARDA DE MENOR',
      'USUCAPIÃO',
      'Verbas + Danos',
      'verbas diversas',
      'Verbas Remuneratórias indeniza',
      ': Verbas Rescisórias',
      'VT + DM',
      'VT - PEDIDOS NOVOS'
    ]

    for (const name of names) {
      await queryRunner.query(
        `INSERT INTO "action_objects" ("id", "name") VALUES ($1, $2) ON CONFLICT DO NOTHING`,
        [uuidv4(), name],
      )
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM "action_objects"`)
  }
}
